#!/usr/bin/env python3
"""Sync the profile's linked, circular avatars without changing API order/filters."""

import io
import json
import re
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from urllib.parse import parse_qsl, quote, urlencode, urlsplit, urlunsplit
from urllib.request import Request, urlopen

from PIL import Image, ImageChops, ImageDraw, ImageOps

ROOT = Path(__file__).resolve().parents[1]
# Keep the original SVG's parameters, including its default pagination and bots.
API_URL = (
    "https://contrib.hoa.moe/api/json?org=HITSZ-OpenAuto"
    "&exclude=.github&repo=noname7321/HITSZ-OpenAuto"
)
START = "<!-- contributors:start -->"
END = "<!-- contributors:end -->"
LOGIN = re.compile(r"[A-Za-z0-9][A-Za-z0-9-]{0,38}(?:\[bot\])?\Z")
AVATAR_PATH = re.compile(r"/(?:u|in)/[0-9]+\Z")
PIXELS = 128
MAX_BYTES = 5 * 1024 * 1024


def fetch_bytes(url):
    request = Request(url, headers={"User-Agent": "HITSZ-OpenAuto-profile-sync"})
    with urlopen(request, timeout=30) as response:
        data = response.read(MAX_BYTES + 1)
    if len(data) > MAX_BYTES:
        raise ValueError("Response is too large")
    return data


def validate_contributors(data):
    """Fail closed: never turn an error/empty/invalid response into an empty grid."""
    if not isinstance(data, list) or not data:
        raise ValueError("Expected a non-empty contributor list")
    seen = set()
    for user in data:
        if not isinstance(user, dict):
            raise ValueError("Invalid contributor entry")
        login = user.get("login")
        if not isinstance(login, str) or not LOGIN.fullmatch(login):
            raise ValueError("Invalid contributor login")
        if login.casefold() in seen:
            raise ValueError(f"Duplicate contributor: {login}")
        seen.add(login.casefold())
        if user.get("type") not in ("User", "Bot"):
            raise ValueError(f"Invalid contributor type: {login}")
        url = user.get("avatar_url")
        if not isinstance(url, str):
            raise ValueError(f"Missing avatar URL: {login}")
        parsed = urlsplit(url)
        if (
            parsed.scheme != "https"
            or parsed.netloc != "avatars.githubusercontent.com"
            or not AVATAR_PATH.fullmatch(parsed.path)
            or parsed.fragment
        ):
            raise ValueError(f"Unexpected avatar URL: {login}")
    # The API already deduplicates and orders contributors. Do not sort or filter.
    return data


def avatar_url(user):
    parsed = urlsplit(user["avatar_url"])
    query = [(key, value) for key, value in parse_qsl(parsed.query) if key != "s"]
    query.append(("s", str(PIXELS)))
    return urlunsplit(parsed._replace(query=urlencode(query)))


def circular_avatar(data):
    with Image.open(io.BytesIO(data)) as source:
        if source.width > 4096 or source.height > 4096:
            raise ValueError("Avatar dimensions are too large")
        avatar = ImageOps.fit(source.convert("RGBA"), (PIXELS, PIXELS), Image.Resampling.LANCZOS)
    # Bake transparency into the PNG: GitHub strips README CSS border-radius.
    mask = Image.new("L", (PIXELS * 4, PIXELS * 4))
    ImageDraw.Draw(mask).ellipse((0, 0, PIXELS * 4 - 1, PIXELS * 4 - 1), fill=255)
    mask = mask.resize((PIXELS, PIXELS), Image.Resampling.LANCZOS)
    avatar.putalpha(ImageChops.multiply(avatar.getchannel("A"), mask))
    output = io.BytesIO()
    avatar.save(output, format="PNG", optimize=True)
    return output.getvalue()


def profile_url(user):
    login = user["login"]
    # GitHub App bots have an app page rather than a /name[bot] user page.
    if user["type"] == "Bot" and login.endswith("[bot]"):
        return "https://github.com/apps/" + quote(login[:-5], safe="")
    return "https://github.com/" + quote(login, safe="")


def render_block(users):
    lines = [START, "<!-- Generated by scripts/sync_contributors.py; do not edit this block. -->", "<p>"]
    for index, user in enumerate(users):
        login = user["login"]
        src = "../images/contributors/" + quote(login, safe="") + ".png"
        lines.append(
            f'<a href="{profile_url(user)}"><img src="{src}" width="64" height="64" '
            f'alt="@{login}" title="@{login}" /></a>'
        )
        if (index + 1) % 12 == 0 and index + 1 < len(users):
            lines.append("<br />")
    return "\n".join([*lines, "</p>", END])


def replace_block(readme, block):
    if readme.count(START) != 1 or readme.count(END) != 1:
        raise ValueError("README must have exactly one pair of contributor markers")
    start = readme.index(START)
    end = readme.index(END)
    if end < start:
        raise ValueError("Contributor markers are out of order")
    return readme[:start] + block + readme[end + len(END):]


def sync(root=ROOT, fetch=fetch_bytes):
    readme_path = root / "profile/README.md"
    # bytes preserves unrelated content/newlines exactly, even on Windows.
    original = readme_path.read_bytes().decode("utf-8")
    replace_block(original, START + "\n" + END)  # Check markers before network I/O.
    users = validate_contributors(json.loads(fetch(API_URL)))
    updated = replace_block(original, render_block(users)).encode("utf-8")

    def render(user):
        return user["login"] + ".png", circular_avatar(fetch(avatar_url(user)))

    # Fully fetch and render first. API, validation or image failures change no files.
    with ThreadPoolExecutor(max_workers=8) as pool:
        avatars = dict(pool.map(render, users))
    image_dir = root / "images/contributors"
    changed = False
    image_dir.mkdir(parents=True, exist_ok=True)
    for name, data in avatars.items():
        target = image_dir / name
        if not target.exists() or target.read_bytes() != data:
            target.write_bytes(data)
            changed = True
    if readme_path.read_bytes() != updated:
        readme_path.write_bytes(updated)
        changed = True
    for target in image_dir.glob("*.png"):
        if target.name not in avatars:
            target.unlink()
            changed = True
    return len(users), changed


if __name__ == "__main__":
    try:
        count, changed = sync()
        print(f"{'Updated' if changed else 'Unchanged'}: {count} contributors")
    except Exception as error:
        print(f"Contributor sync failed: {error}", file=sys.stderr)
        sys.exit(1)
